baseURL = "https://recambios-aspirador.com/"
title = "Recambios Aspirador"
languageCode = "es"
canonifyURLs = false
enableRobotsTXT = false

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "SITEMAP"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[params]
  defaultDescription = "Recambios compatibles para aspiradores: filtros, baterías, cepillos y más."
